roiback/administrador/urls.py
from django.conf.urls import url

from . import views

app_name = 'administrador'

urlpatterns = [
    url(r'^home', views.home, name='home'),
    url(r'^nuevo_administrador', views.crear_administrador, name='crear_administrador'),
    url(r'^nuevo_asunto', views.crear_asunto, name='crear_asunto'),
    url('crear-comentario/(?P<id_peticion>[0-9]+)/$', views.crear_comentario, name='crear_comentario'),
]

roiback/base/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from . import views

app_name = 'base'

urlpatterns = [
    # redirecciona al template de inicio de sesion
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    # redirecciona al template de inicio de sesion una vez cierre sesion
    path('logout/', LogoutView.as_view(template_name='login.html'), name='logout'),

]

roiback/contacto/urls.py
from django.conf.urls import url

from . import views

app_name = 'contacto'

urlpatterns = [
    url('index/', views.index, name='index'),
    url('edit-peticion/(?P<id_peticion>[0-9]+)/$', views.editar_peticion, name='editar_peticion'),
    url('delete-peticion/(?P<id_peticion>[0-9]+)/$', views.eliminar_peticion, name='eliminar_peticion'),
]

roiback/roiback/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # direcciones del modulo base
    path('base/', include('base.urls')),
    # direcciones del modulo contacto
    path('', include('contacto.urls')),
    # direcciones del modulo admin
    path('administrador/', include('administrador.urls')),
]

roiback/administrador/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _
# Create your models here.


class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

roiback/administrador/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        exclude = ['id','last_login','username' ,'is_staff', 'is_superuser','user_permissions','is_active','date_joined']
        fields = ['first_name', 'last_name', 'email','password1']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control'})
        }
        labels = {
            'first_name': ('Nombre(s)'),
            'last_name': ('Apellidos'),
            'email': ('e-mail'),
            'password1': ('Contraseña'),
        }
        help_texts = {
            'username': '',
            'is_active': '',
            'is_staff': '',
            'groups': '',
        }
    def clean_email(self):
        data = self.cleaned_data['email']
        return data.lower()

roiback/administrador/views.py
from django.shortcuts import render, redirect
from contacto.models import Contacto, Comentario
from contacto.forms import AsuntoForm, ComentarioForm
from administrador.forms import CustomUserCreationForm
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='/login/')
def home(request):
    """Vista que permite visualizar el listado de peticiones"""
    peticiones = Contacto.objects.all()
    return render(request, 'home.html', {'peticiones': peticiones})


@login_required(login_url='/login/')
def crear_administrador(request):
    """Vista que permite crear un nuevo usuario administrador"""
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            usuario = form.save(commit=False)
            usuario.save()
            return redirect('/administrador/home/')
        else:
            return render(request, 'crear_usuario.html', {'form': form})
    else:
        form = CustomUserCreationForm()
        return render(request, 'crear_usuario.html', {'form': form})


@login_required(login_url='/login/')
def crear_asunto(request):
    """Vista que permite crear un nuevo asunto"""
    if request.method == 'POST':
        form = AsuntoForm(request.POST)
        if form.is_valid():
            asunto = form.save(commit=False)
            asunto.save()
            return redirect('/administrador/home/')
        else:
            return render(request, 'crear_asunto.html', {'form': form})
    else:
        form = AsuntoForm()
        return render(request, 'crear_asunto.html', {'form': form})


@login_required(login_url='/login/')
def crear_comentario(request, id_peticion):
    """Vista que permite crear un nuevo comentario"""
    contacto = Contacto.objects.get(pk=id_peticion)
    if request.method == 'POST':
        form = ComentarioForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            comentario = Comentario (
                comentario = data['comentario'],
                contacto = contacto
            )
            comentario.save()
            return redirect('/administrador/home/')
        else:
            return render(request, 'crear_comentario.html', {'form': form})
    else:
        form = ComentarioForm()
        return render(request, 'crear_comentario.html', {'form': form})

roiback/administrador/templates/crear_asunto.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
      <div class="col-lg-8 mb-4">
        <h3>Nuevo Asunto</h3>
        <form  method="post">
          {% csrf_token %}
           <div class="control-group form-group">
            <div class="controls">
              {{form.asunto}}
            </div>
          </div>
          <button type="submit" class="btn btn-success" >Guardar</button>
        </form>
      </div>

    </div>
{% endblock %}

roiback/administrador/templates/crear_comentario.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
      <div class="col-lg-8 mb-4">
        <h3>Nuevo Comentario</h3>
        <form  method="post">
          {% csrf_token %}
           <div class="control-group form-group">
            <div class="controls">
              {{form.comentario}}
            </div>
          </div>
          <button type="submit" class="btn btn-success" >Guardar</button>
        </form>
      </div>

    </div>
{% endblock %}

roiback/administrador/templates/crear_usuario.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
      <div class="col-lg-8 mb-4">
        <h3>Nuevo Administrador</h3>
        <form name="sentMessage" id="contactForm" method="post">
          {% csrf_token %}
           <div class="control-group form-group">
            <div class="controls">
              {{form}}
            </div>
          </div>
          <button type="submit" class="btn btn-success" id="">Guardar</button>
        </form>
      </div>

    </div>
{% endblock %}

roiback/administrador/templates/home.html
{% extends 'base.html' %}
{% block content %}
    <div>
        <a class="btn btn-primary" href="{% url 'administrador:crear_administrador'%}">Registrar Administrador</a>
        <a class="btn btn-warning" href="{% url 'administrador:crear_asunto'%}">Crear Asunto</a>
        <a class="btn btn-danger" href="{% url 'base:logout' %}">Cerrar Sesión</a>


    </div>
    <div class="row">
      <div class="col-md-5">
        <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nombres</th>
      <th scope="col">Apellidos</th>
      <th scope="col">Fecha de Nacimiento</th>
        <th scope="col">Genero</th>
        <th scope="col">Tipo de Documento</th>
        <th scope="col">Numero de Documento</th>
        <th scope="col">Email</th>
        <th scope="col">Telefono de Contacto</th>
        <th scope="col">Asunto</th>
        <th scope="col">Editar</th>
        <th scope="col">Eliminar</th>
        <th scope="col">Comentario</th>
    </tr>
  </thead>
  <tbody>
  {% for peticion in peticiones %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td>{{peticion.nombre}}</td>
      <td>{{peticion.apellido}}</td>
      <td>{{peticion.fecha_nacimiento}}</td>
        <td>{{peticion.genero}}</td>
      <td>{{peticion.tipo_documento}}</td>
      <td>{{peticion.numero_documento}}</td>
        <td>{{peticion.email}}</td>
      <td>{{peticion.telefono_contacto}}</td>
      <td>{{peticion.asunto}}</td>
        <td>
            <a class="btn btn-primary btn-sm" href="{% url 'contacto:editar_peticion' peticion.id  %}">
                Editar
            </a>

        </td>
        <td>
           <a class="btn btn-info btn-sm" href="{% url 'contacto:eliminar_peticion' peticion.id  %}">
                Eliminar
            </a>
        </td>
        <td>

            <a class="btn btn-info btn-sm" href="{% url 'administrador:crear_comentario' peticion.id  %}">
                Agregar
            </a>
        </td>
    </tr>
  {% endfor %}
  </tbody>
</table>
      </div>
    </div>
{% endblock %}