roiback/base/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from . import views

app_name = 'base'

urlpatterns = [
    # redirecciona al template de inicio de sesion
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    # redirecciona al template de inicio de sesion una vez cierre sesion
    path('logout/', LogoutView.as_view(template_name='login.html'), name='logout'),

]

roiback/contacto/urls.py
from django.conf.urls import url

from . import views

app_name = 'contacto'

urlpatterns = [
    url('index/', views.index, name='index'),
    url('edit-peticion/(?P<id_peticion>[0-9]+)/$', views.editar_peticion, name='editar_peticion'),
    url('delete-peticion/(?P<id_peticion>[0-9]+)/$', views.eliminar_peticion, name='eliminar_peticion'),
]

roiback/roiback/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # direcciones del modulo base
    path('base/', include('base.urls')),
    # direcciones del modulo contacto
    path('', include('contacto.urls')),
    # direcciones del modulo admin
    path('administrador/', include('administrador.urls')),
]

roiback/contacto/models.py
from django.db import models
from contacto.choices import GENERO_CHOICES, TIPO_DOCUMENTO_CHOICES


class Asunto(models.Model):
    asunto = models.CharField(max_length=100, null=False)
    def __str__(self):
        return self.asunto


class Contacto(models.Model):
    nombre = models.CharField(max_length=100, null=False)
    apellido = models.CharField(max_length=100, null=False)
    fecha_nacimiento = models.DateField()
    genero = models.CharField(max_length=100,choices=GENERO_CHOICES, null=False)
    tipo_documento = models.CharField(max_length=100,choices=TIPO_DOCUMENTO_CHOICES, null=False)
    numero_documento = models.CharField(max_length=100, null=False)
    email = models.EmailField(max_length = 254)
    telefono_contacto = models.CharField(max_length=100, null=False)
    asunto = models.ForeignKey(Asunto, on_delete=models.CASCADE, null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comentario(models.Model):
    comentario = models.CharField(max_length=200, null=True)
    contacto = models.ForeignKey(Contacto, on_delete=models.CASCADE, null=False, blank=False)

roiback/contacto/forms.py
from django import forms
from .models import *


class DateInput(forms.DateInput):
    input_type = 'date'


class ContactoForm(forms.ModelForm):
    class Meta:
        model = Contacto
        fields = ['nombre', 'apellido', 'fecha_nacimiento',
                  'genero', 'tipo_documento', 'numero_documento',
                  'email', 'telefono_contacto', 'asunto' ]
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'apellido': forms.TextInput(attrs={'class': 'form-control'}),
            'fecha_nacimiento': DateInput(),
            'genero': forms.Select(attrs={'class': 'form-control'}),
            'tipo_documento': forms.Select(attrs={'class': 'form-control'}),
            'numero_documento': forms.NumberInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'telefono_contacto': forms.NumberInput(attrs={'class': 'form-control'}),
            'asunto': forms.Select(attrs={'class': 'form-control'})
        }
        labels = {
            'nombre': ('Nombres'),
            'apellido': ('Apellidos'),
            'fecha_nacimiento': ('Fecha Nacimiento'),
            'genero': ('Genero'),
            'tipo_documento': ('Tipo de Documento'),
            'numero_documento': ('Numero de Documento'),
            'email': ('Email'),
            'telefono_contacto': ('Telefono de Contacto'),
            'asunto':('Asunto')
        }

class AsuntoForm(forms.ModelForm):
    class Meta:
        model = Asunto
        fields = ['asunto']
        widgets = {
            'asunto': forms.TextInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'asunto': ('Asunto'),
        }


class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ['comentario']
        widgets = {
            'comentario': forms.TextInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'comentario': ('Comentario'),
        }

roiback/contacto/views.py
from django.shortcuts import render, redirect
from contacto.forms import *
from contacto.models import *


def index(request):
    """Vista que carga el formulario de contacto"""
    if request.method == 'POST':
        form = ContactoForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            contacto = form.save()
            return redirect('/index/')
        else:
            print("Formulario no valido")
            return render(request, "formulario.html", {'form': form})
    else:
        form = ContactoForm()
        return render(request, "formulario.html", {'form': form,})


def editar_peticion(request, id_peticion):
    """Vista que permite editar los valores de un registro"""

    peticion = Contacto.objects.get(pk=id_peticion)
    peticiones = Contacto.objects.all()

    if request.method == 'GET':
        # Get se usa para obtener datos del formulario
        form = ContactoForm(instance=peticion)
    else:
        # Aqui guardamos la peticion
        form = ContactoForm(request.POST, instance=peticion)
        if form.is_valid():
            form.save()
            return render(request, 'home.html', {'peticiones': peticiones})
    return render(request, 'editar_peticion.html', {'form': form})


def eliminar_peticion(request, id_peticion):
    """Vista que permite eliminar un registro de peticion"""
    peticion = Contacto.objects.get(pk=id_peticion)
    peticion.delete()
    peticiones = Contacto.objects.all()
    return render(request, 'home.html', {'peticiones': peticiones})

roiback/contacto/templates/editar_peticion.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
      <div class="col-lg-8 mb-4">
        <h3>Contacto</h3>
        <form name="sentMessage" id="contactForm" method="post">
          {% csrf_token %}
          <div class="control-group form-group">
            <div class="controls">
              <label>Nombres:</label>
              {{form.nombre}}
              <p class="help-block"></p>
            </div>
          </div>
          <div class="control-group form-group">
            <div class="controls">
              <label>Apellidos:</label>
              {{form.apellido}}
            </div>
          </div>
          <div class="control-group form-group">
            <div class="controls">
              <label>Fecha Nacimiento:</label>
              {{form.fecha_nacimiento}}
            </div>
          </div>
          <div class="control-group form-group">
            <div class="controls">
              <label>Genero:</label>
              {{form.genero}}
            </div>
          </div>
           <div class="control-group form-group">
            <div class="controls">
              <label>Tipo de Documento:</label>
              {{form.tipo_documento}}
            </div>
          </div>
            <div class="control-group form-group">
            <div class="controls">
              <label>Número de Documento:</label>
              {{form.numero_documento}}
            </div>
          </div>
          <div class="control-group form-group">
            <div class="controls">
              <label>Email:</label>
              {{form.email}}
            </div>
          </div>
           <div class="control-group form-group">
            <div class="controls">
              <label>Telefono de Contacto:</label>
              {{form.telefono_contacto}}
            </div>
          </div>
            <div class="control-group form-group">
            <div class="controls">
              <label>Asunto:</label>
              {{form.asunto}}
            </div>
          </div>
          <button type="submit" class="btn btn-primary" id="sendMessageButton">Enviar</button>
        </form>
      </div>

    </div>
{% endblock %}

roiback/contacto/templates/formulario.html
{% extends 'base.html' %}
{% block content %}
<div>
  <a class="btn btn-primary" href="{% url 'base:login' %}">Iniciar Sesión</a>
</div>
<div class="row">

      <div class="col-lg-8 mb-4">
        <h3>Contacto</h3>
        <form name="sentMessage" id="contactForm" method="post">
          {% csrf_token %}
          <div class="control-group form-group">
            <div class="controls">
              <label>Nombres:</label>
              {{form.nombre}}
              <p class="help-block"></p>
            </div>
          </div>
          <div class="control-group form-group">
            <div class="controls">
              <label>Apellidos:</label>
              {{form.apellido}}
            </div>
          </div>
          <div class="control-group form-group">
            <div class="controls">
              <label>Fecha Nacimiento:</label>
              {{form.fecha_nacimiento}}
            </div>
          </div>
          <div class="control-group form-group">
            <div class="controls">
              <label>Genero:</label>
              {{form.genero}}
            </div>
          </div>
           <div class="control-group form-group">
            <div class="controls">
              <label>Tipo de Documento:</label>
              {{form.tipo_documento}}
            </div>
          </div>
            <div class="control-group form-group">
            <div class="controls">
              <label>Número de Documento:</label>
              {{form.numero_documento}}
            </div>
          </div>
          <div class="control-group form-group">
            <div class="controls">
              <label>Email:</label>
              {{form.email}}
            </div>
          </div>
           <div class="control-group form-group">
            <div class="controls">
              <label>Telefono de Contacto:</label>
              {{form.telefono_contacto}}
            </div>
          </div>
            <div class="control-group form-group">
            <div class="controls">
              <label>Asunto:</label>
              {{form.asunto}}
            </div>
          </div>
          <button type="submit" class="btn btn-primary" id="sendMessageButton">Enviar</button>
        </form>
      </div>

    </div>
{% endblock %}